framework:
  messenger:
    failure_transport: failed
    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      # async: '%env(MESSENGER_TRANSPORT_DSN)%'
      # failed: 'doctrine://default?queue_name=failed'
      sync: 'sync://'

      async_priority_high:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        retry_strategy:
          # milliseconds delay, 30 seconds
          delay: 30000
        options:
          queue_name: high

      async_priority_normal:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        retry_strategy:
          # milliseconds delay, 30 seconds
          delay: 30000
        options:
          queue_name: normal

      async_priority_low:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        retry_strategy:
          # milliseconds delay, 30 seconds
          delay: 30000
        options:
          queue_name: low

      failed: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=failed'

    default_bus: messenger.bus.default
    buses:
      messenger.bus.default:
        middleware:
          # each time a message is handled, the Doctrine connection
          # is "pinged" and reconnected if it's closed.
          - doctrine_ping_connection
          # After handling, the Doctrine connection is closed
          - doctrine_close_connection

when@test:
   framework:
       messenger:
           transports:
               # replace with your transport name here (e.g., my_transport: 'in-memory://')
               # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
               async: 'in-memory://'
               failed: 'in-memory://'
