twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller:  null
    paths:
        '%kernel.project_dir%/custom/templates': ~
