framework:
    templating:
        engines:
        - twig

twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller:  App\Controller\ExceptionController::showAction
    paths:
        '%kernel.project_dir%/custom/templates': ~
