imports:
    - { resource: parameters.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    serializer:
        enabled: false
    profiler:
        enabled: false
        collect: false

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        "%kernel.root_dir%/../custom/email_templates": custom_email_templates

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: "%database_mysql_version%"
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_rest:
    routing_loader:
        default_format: json
    param_fetcher_listener: true
    body_listener: true
    body_converter:
        enabled: true
    format_listener: true
    view:
        view_response_listener: force
        formats:
            xml: true
            json : true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    exception:
        enabled: true
        codes:
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': 404
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Ilios\CoreBundle\Exception\InvalidInputWithSafeUserMessageException': 400
            'Symfony\Component\HttpKernel\Exception\ServiceUnavailableHttpException': 500
        messages:
            'Ilios\CoreBundle\Exception\InvalidInputWithSafeUserMessageException': true


nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
        expose_headers: ['*']
        max_age: 3600
    paths:
        '^/':

nelmio_api_doc:
    name: Ilios API
    sandbox:
        body_format:
            formats:
                - form
                - json
            default_format: json
        request_format:
            formats:
                json: application/json
                xml: application/xml
            method: format_param
            default_format: json

sensio_framework_extra:
    request: { converters: true }
    view:    { annotations: false }
    router:  { annotations: true }

jms_di_extra:
    locations:
        all_bundles: false
        bundles: ["@IliosCoreBundle"]

security:
    encoders:
        Ilios\CoreBundle\Entity\User:
            algorithm: bcrypt
        ilios_legacy_encoder:
            id: ilios_authentication.form.legacy_encoder
            
doctrine_migrations:
    dir_name: "%kernel.root_dir%/Resources/DoctrineMigrations"
    name: Ilios Migrations
    namespace: Ilios\Migrations

exercise_html_purifier:
    default:
        Cache.SerializerPath: "%kernel.cache_dir%/htmlpurifier"
        HTML.Allowed: "a[href],br,div,dd,dl,dt,em,li,ol,p,strong,sub,sup,ul,u"

ilios_core:
    file_system_storage_path: "%file_system_storage_path%"
    ldap_directory_url: "%ldap_directory_url%"
    ldap_directory_user: "%ldap_directory_user%"
    ldap_directory_password: "%ldap_directory_password%"
    ldap_directory_search_base: "%ldap_directory_search_base%"
    ldap_directory_campus_id_property: "%ldap_directory_campus_id_property%"
    ldap_directory_username_property: "%ldap_directory_username_property%"
    institution_domain: "%institution_domain%"
    supporting_link: "%supporting_link%"
    timezone: "%timezone%"

ilios_authentication:
    legacy_salt: "%legacy_password_salt%"
    type: "%authentication_type%"
    ldap_authentication_host: "%ldap_authentication_host%"
    ldap_authentication_port: "%ldap_authentication_port%"
    ldap_authentication_bind_template: "%ldap_authentication_bind_template%"
