services:
    iliosweb.assets:
        class: Ilios\WebBundle\Service\WebAssets
        arguments:    [%ilios_web.environment%, %ilios_web.version%, %ilios_web.bucket_url%, %kernel.cache_dir%]
    iliosweb.jsonindex:
        class: Ilios\WebBundle\Service\WebIndexFromJson
        arguments:    ['@templating']
