parameters:
  locale: 'en'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  App\Tests\DataLoader\:
    public: true
    resource: '%kernel.project_dir%/tests/DataLoader'

  App\Tests\Fixture\:
    resource: '%kernel.project_dir%/tests/Fixture'

  # public in tests only for JsonControllerTest access
  App\Service\JsonWebTokenManager:
    public: true

  App\Repository\ApplicationConfigRepository:
    arguments:
      $cacheEnabled: false

  # public in tests only for ImportMeshUniverseCommandAcceptanceTest access
  Ilios\MeSH\Parser:
    public: true

  # public in tests only for ImportMeshUniverseCommandAcceptanceTest access
  App\Service\Index\Mesh:
    public: true
