Program:
 type: object
 properties:
  id:
   description: Id
   type: integer
   readOnly: true
  title:
   description: Title
   type: string
  shortTitle:
   description: Shorttitle
   type: string
  duration:
   description: Duration
   type: integer
  publishedAsTbd:
   description: Publishedastbd
   type: boolean
   deprecated: true
  published:
   description: Published
   type: boolean
   deprecated: true
  school:
   description: School
   type: string
  programYears:
   description: Programyears
   type: array
   items:
    type: string
  curriculumInventoryReports:
   description: Curriculuminventoryreports
   type: array
   items:
    type: string
  directors:
   description: Directors
   type: array
   items:
    type: string
