services:
    security.access.aamc_method_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\AamcMethodEntityVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.aamc_pcrs_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\AamcPcrsEntityVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.aamc_resource_type_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\AamcResourceTypeEntityVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.alert_change_type_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\AlertChangeTypeEntityVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.alert_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\AlertEntityVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.assessment_option_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\AssessmentOptionEntityVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.authentication_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\AuthenticationEntityVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.cohort_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\CohortEntityVoter
        parent: security.access.entity.program_year_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.competency_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\CompetencyEntityVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.course_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\CourseEntityVoter
        parent: security.access.course_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.learner_group_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\LearnerGroupEntityVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.mesh_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\MeshEntityVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.objective_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\ObjectiveEntityVoter
        arguments: [  "@ilioscore.programyearsteward.manager" ]
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.program_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\ProgramEntityVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.program_year_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\ProgramYearEntityVoter
        arguments: [  "@ilioscore.programyearsteward.manager" ]
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.school_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\SchoolEntityVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.session_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\SessionEntityVoter
        parent: security.access.course_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.session_type_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\SessionTypeEntityVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.term_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\TermEntityVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.user_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\UserEntityVoter
        public: false
        tags:
            - { name: security.voter }
