services:
    security.access.entity.course_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\CourseEntityVoter
        parent: security.access.course_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.session_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\SessionEntityVoter
        parent: security.access.course_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.term_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\TermEntityVoter
        arguments: [ @ilioscore.permission.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.user_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\UserEntityVoter
        arguments: [ @ilioscore.permission.manager ]
        public: false
        tags:
            - { name: security.voter }
