services:
    security.access.entity.cohort_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\CohortEntityVoter
        parent: security.access.entity.program_year_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.course_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\CourseEntityVoter
        parent: security.access.course_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.mesh_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\MeshEntityVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.program_year_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\ProgramYearEntityVoter
        arguments: [ @ilioscore.permission.manager, @ilioscore.programyearsteward.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.school_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\SchoolEntityVoter
        arguments: [ @ilioscore.permission.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.session_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\SessionEntityVoter
        parent: security.access.course_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.term_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\TermEntityVoter
        arguments: [ @ilioscore.permission.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.entity.user_voter:
        class: Ilios\AuthenticationBundle\Voter\Entity\UserEntityVoter
        arguments: [ @ilioscore.permission.manager ]
        public: false
        tags:
            - { name: security.voter }
