services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ilios\AuthenticationBundle\:
            resource: '../../*'

    Ilios\AuthenticationBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Ilios\AuthenticationBundle\Listener\AddJwtHeader:
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    Ilios\AuthenticationBundle\Service\JsonWebTokenManager:
        public: true
        arguments:
          $secretKey: '%kernel.secret%'

    Ilios\AuthenticationBundle\Service\AuthenticationFactory:
        public: true

    Ilios\AuthenticationBundle\Service\AuthenticationInterface:
        factory: ['@Ilios\AuthenticationBundle\Service\AuthenticationFactory', createAuthenticationService]

    Ilios\AuthenticationBundle\Service\CasManager:
        public: true
