services:
    security.access.archivable_voter:
        class: Ilios\AuthenticationBundle\Voter\ArchivableVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.course_learning_material_voter:
        class: Ilios\AuthenticationBundle\Voter\CourseLearningMaterialVoter
        parent: security.access.course_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.course_voter:
        class: Ilios\AuthenticationBundle\Voter\CourseVoter
        arguments: [ "@ilioscore.course.manager"]
        public: false
    security.access.curriculum_inventory_academic_level_voter:
        class: Ilios\AuthenticationBundle\Voter\CurriculumInventoryAcademicLevelVoter
        parent: security.access.curriculum_inventory_report_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.curriculum_inventory_export_voter:
        class: Ilios\AuthenticationBundle\Voter\CurriculumInventoryExportVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.curriculum_inventory_institution_voter:
        class: Ilios\AuthenticationBundle\Voter\CurriculumInventoryInstitutionVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.curriculum_inventory_report_voter:
        class: Ilios\AuthenticationBundle\Voter\CurriculumInventoryReportVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.curriculum_sequence_block_voter:
        class: Ilios\AuthenticationBundle\Voter\CurriculumInventorySequenceBlockVoter
        parent: security.access.curriculum_inventory_report_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.curriculum_sequence_voter:
        class: Ilios\AuthenticationBundle\Voter\CurriculumInventorySequenceVoter
        parent: security.access.curriculum_inventory_report_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.ilm_session_voter:
        class: Ilios\AuthenticationBundle\Voter\IlmSessionVoter
        parent: security.access.entity.session_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.ingestion_exception_voter:
        class: Ilios\AuthenticationBundle\Voter\IngestionExceptionVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.instructor_group_voter:
        class: Ilios\AuthenticationBundle\Voter\InstructorGroupVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.learning_material_status_voter:
        class: Ilios\AuthenticationBundle\Voter\LearningMaterialStatusVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.learning_material_user_role_voter:
        class: Ilios\AuthenticationBundle\Voter\LearningMaterialUserRoleVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.learning_material_voter:
        class: Ilios\AuthenticationBundle\Voter\LearningMaterialVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.lockable_voter:
        class: Ilios\AuthenticationBundle\Voter\LockableVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.offering_voter:
        class: Ilios\AuthenticationBundle\Voter\OfferingVoter
        parent: security.access.entity.session_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.pending_user_update_voter:
        class: Ilios\AuthenticationBundle\Voter\PendingUserUpdateVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.permission_voter:
        class: Ilios\AuthenticationBundle\Voter\PermissionVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.program_year_steward_voter:
        class: Ilios\AuthenticationBundle\Voter\ProgramYearStewardVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.report_voter:
        class: Ilios\AuthenticationBundle\Voter\ReportVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.school_config_voter:
        class: Ilios\AuthenticationBundle\Voter\SchoolConfigVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.school_event_voter:
        class: Ilios\AuthenticationBundle\Voter\SchooleventVoter
        arguments: [ "@ilioscore.school.manager" ]
        public: false
        tags:
            - { name: security.voter }
    security.access.session_description_voter:
        class: Ilios\AuthenticationBundle\Voter\SessionDescriptionVoter
        parent: security.access.entity.session_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.session_learning_material_voter:
        class: Ilios\AuthenticationBundle\Voter\SessionLearningMaterialVoter
        parent: security.access.entity.session_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.temporary_filesystem_voter:
        class: Ilios\AuthenticationBundle\Voter\TemporaryFileSystemVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.userevent_voter:
        class: Ilios\AuthenticationBundle\Voter\UsereventVoter
        arguments: [ "@ilioscore.user.manager" ]
        public: false
        tags:
            - { name: security.voter }
    security.access.user_made_reminder_voter:
        class: Ilios\AuthenticationBundle\Voter\UserMadeReminderVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.user_role_voter:
        class: Ilios\AuthenticationBundle\Voter\UserRoleVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.vocabulary_voter:
        class: Ilios\AuthenticationBundle\Voter\VocabularyVoter
        public: false
        tags:
            - { name: security.voter }
