services:
    security.access.aamc_method_voter:
        class: Ilios\AuthenticationBundle\Voter\AamcMethodVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.aamc_pcrs_voter:
        class: Ilios\AuthenticationBundle\Voter\AamcPcrsVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.alert_change_type_voter:
        class: Ilios\AuthenticationBundle\Voter\AlertChangeTypeVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.alert_voter:
        class: Ilios\AuthenticationBundle\Voter\AlertVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.archivable_voter:
        class: Ilios\AuthenticationBundle\Voter\ArchivableVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.assessment_option_voter:
        class: Ilios\AuthenticationBundle\Voter\AssessmentOptionVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.cohort_voter:
        class: Ilios\AuthenticationBundle\Voter\CohortVoter
        parent: security.access.program_year_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.competency_voter:
        class: Ilios\AuthenticationBundle\Voter\CompetencyVoter
        arguments: [ @ilioscore.permission.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.course_clerkship_type_voter:
        class: Ilios\AuthenticationBundle\Voter\CourseClerkshipTypeVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.course_learning_material_voter:
        class: Ilios\AuthenticationBundle\Voter\CourseLearningMaterialVoter
        parent: security.access.course_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.course_voter:
        class: Ilios\AuthenticationBundle\Voter\CourseVoter
        arguments: [ @ilioscore.course.manager, @ilioscore.permission.manager ]
        public: false
    security.access.curriculum_inventory_academic_level_voter:
        class: Ilios\AuthenticationBundle\Voter\CurriculumInventoryAcademicLevelVoter
        parent: security.access.curriculum_inventory_report_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.curriculum_inventory_export_voter:
        class: Ilios\AuthenticationBundle\Voter\CurriculumInventoryExportVoter
        arguments: [ @ilioscore.permission.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.curriculum_inventory_institution_voter:
        class: Ilios\AuthenticationBundle\Voter\CurriculumInventoryInstitutionVoter
        arguments: [ @ilioscore.permission.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.curriculum_inventory_report_voter:
        class: Ilios\AuthenticationBundle\Voter\CurriculumInventoryReportVoter
        arguments: [ @ilioscore.permission.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.curriculum_sequence_block_session_voter:
        class: Ilios\AuthenticationBundle\Voter\CurriculumInventorySequenceBlockSessionVoter
        parent: security.access.curriculum_inventory_report_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.curriculum_sequence_block_voter:
        class: Ilios\AuthenticationBundle\Voter\CurriculumInventorySequenceBlockVoter
        parent: security.access.curriculum_inventory_report_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.curriculum_sequence_voter:
        class: Ilios\AuthenticationBundle\Voter\CurriculumInventorySequenceVoter
        parent: security.access.curriculum_inventory_report_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.department_voter:
        class: Ilios\AuthenticationBundle\Voter\DepartmentVoter
        arguments: [ @ilioscore.permission.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.ilm_session_voter:
        class: Ilios\AuthenticationBundle\Voter\IlmSessionVoter
        parent: security.access.session_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.ingestion_exception_voter:
        class: Ilios\AuthenticationBundle\Voter\IngestionExceptionVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.instructor_group_voter:
        class: Ilios\AuthenticationBundle\Voter\InstructorGroupVoter
        arguments: [ @ilioscore.permission.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.learner_group_voter:
        class: Ilios\AuthenticationBundle\Voter\LearnerGroupVoter
        arguments: [ @ilioscore.permission.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.learning_material_status_voter:
        class: Ilios\AuthenticationBundle\Voter\LearningMaterialStatusVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.learning_material_user_role_voter:
        class: Ilios\AuthenticationBundle\Voter\LearningMaterialUserRoleVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.learning_material_voter:
        class: Ilios\AuthenticationBundle\Voter\LearningMaterialVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.lockable_voter:
        class: Ilios\AuthenticationBundle\Voter\LockableVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.mesh_voter:
        class: Ilios\AuthenticationBundle\Voter\MeshVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.objective_voter:
        class: Ilios\AuthenticationBundle\Voter\ObjectiveVoter
        arguments: [ @ilioscore.permission.manager, @ilioscore.programyearsteward.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.offering_voter:
        class: Ilios\AuthenticationBundle\Voter\OfferingVoter
        parent: security.access.session_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.pending_user_update_voter:
        class: Ilios\AuthenticationBundle\Voter\PendingUserUpdateVoter
        arguments: [ @ilioscore.permission.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.permission_voter:
        class: Ilios\AuthenticationBundle\Voter\PermissionVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.program_voter:
        class: Ilios\AuthenticationBundle\Voter\ProgramVoter
        arguments: [ @ilioscore.permission.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.program_year_steward_voter:
        class: Ilios\AuthenticationBundle\Voter\ProgramYearStewardVoter
        arguments: [ @ilioscore.permission.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.program_year_voter:
        class: Ilios\AuthenticationBundle\Voter\ProgramYearVoter
        arguments: [ @ilioscore.permission.manager, @ilioscore.programyearsteward.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.report_voter:
        class: Ilios\AuthenticationBundle\Voter\ReportVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.school_event_voter:
        class: Ilios\AuthenticationBundle\Voter\SchooleventVoter
        arguments: [ @ilioscore.permission.manager, @ilioscore.school.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.school_voter:
        class: Ilios\AuthenticationBundle\Voter\SchoolVoter
        arguments: [ @ilioscore.permission.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.session_voter:
        class: Ilios\AuthenticationBundle\Voter\SessionVoter
        parent: security.access.course_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.session_description_voter:
        class: Ilios\AuthenticationBundle\Voter\SessionDescriptionVoter
        parent: security.access.session_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.session_learning_material_voter:
        class: Ilios\AuthenticationBundle\Voter\SessionLearningMaterialVoter
        parent: security.access.session_voter
        public: false
        tags:
            - { name: security.voter }
    security.access.session_type_voter:
        class: Ilios\AuthenticationBundle\Voter\SessionTypeVoter
        arguments: [ @ilioscore.permission.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.temporary_filesystem_voter:
        class: Ilios\AuthenticationBundle\Voter\TemporaryFileSystemVoter
        arguments: [ @ilioscore.permission.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.term_voter:
        class: Ilios\AuthenticationBundle\Voter\TermVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.topic_voter:
        class: Ilios\AuthenticationBundle\Voter\TopicVoter
        arguments: [ @ilioscore.permission.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.userevent_voter:
        class: Ilios\AuthenticationBundle\Voter\UsereventVoter
        arguments: [ @ilioscore.user.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.user_made_reminder_voter:
        class: Ilios\AuthenticationBundle\Voter\UserMadeReminderVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.user_role_voter:
        class: Ilios\AuthenticationBundle\Voter\UserRoleVoter
        public: false
        tags:
            - { name: security.voter }
    security.access.user_voter:
        class: Ilios\AuthenticationBundle\Voter\UserVoter
        arguments: [ @ilioscore.permission.manager ]
        public: false
        tags:
            - { name: security.voter }
    security.access.vocabulary_voter:
        class: Ilios\AuthenticationBundle\Voter\VocabularyVoter
        public: false
        tags:
            - { name: security.voter }
