security:
    providers:
        main:
            entity:
                class: Ilios\CoreBundle\Entity\User
                property: userId
    role_hierarchy:
        ROLE_Course Director:       ROLE_Student
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        ilios_legacy_secured:
            pattern:   ^/
            stateless: true
            ilios_legacy_ci: true
    access_control:
        - { path: ^/, roles: ROLE_Student }
