parameters:
    ilioscore.form.handler.class: Ilios\CoreBundle\Form\Handler

services:
    ilioscore.aamcmethod.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.aamcmethod.manager", '@form.factory', Ilios\CoreBundle\Form\Type\AamcMethodType]
    ilioscore.aamcpcrs.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.aamcpcrs.manager", '@form.factory', Ilios\CoreBundle\Form\Type\AamcPcrsType]
    ilioscore.aamcresourcetype.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.aamcresourcetype.manager", '@form.factory', Ilios\CoreBundle\Form\Type\AamcResourceTypeType]
    ilioscore.alertchangetype.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.alertchangetype.manager", '@form.factory', Ilios\CoreBundle\Form\Type\AlertChangeTypeType]
    ilioscore.alert.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.alert.manager", '@form.factory', Ilios\CoreBundle\Form\Type\AlertType]
    ilioscore.assessmentoption.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.assessmentoption.manager", '@form.factory', Ilios\CoreBundle\Form\Type\AssessmentOptionType]
    ilioscore.authentication.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.authentication.manager", '@form.factory', Ilios\CoreBundle\Form\Type\AuthenticationType]
    ilioscore.cohort.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.cohort.manager", '@form.factory', Ilios\CoreBundle\Form\Type\CohortType]
    ilioscore.competency.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.competency.manager", '@form.factory', Ilios\CoreBundle\Form\Type\CompetencyType]
    ilioscore.courseclerkshiptype.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.courseclerkshiptype.manager", '@form.factory', Ilios\CoreBundle\Form\Type\CourseClerkshipTypeType]
    ilioscore.courselearningmaterial.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.courselearningmaterial.manager", '@form.factory', Ilios\CoreBundle\Form\Type\CourseLearningMaterialType]
    ilioscore.course.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.course.manager", '@form.factory', Ilios\CoreBundle\Form\Type\CourseType]
    ilioscore.curriculuminventoryacademiclevel.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.curriculuminventoryacademiclevel.manager", '@form.factory', Ilios\CoreBundle\Form\Type\CurriculumInventoryAcademicLevelType]
    ilioscore.curriculuminventoryexport.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.curriculuminventoryexport.manager", '@form.factory', Ilios\CoreBundle\Form\Type\CurriculumInventoryExportType]
    ilioscore.curriculuminventoryinstitution.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.curriculuminventoryinstitution.manager", '@form.factory', Ilios\CoreBundle\Form\Type\CurriculumInventoryInstitutionType]
    ilioscore.curriculuminventoryreport.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.curriculuminventoryreport.manager", '@form.factory', Ilios\CoreBundle\Form\Type\CurriculumInventoryReportType]
    ilioscore.curriculuminventorysequenceblock.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.curriculuminventorysequenceblock.manager", '@form.factory', Ilios\CoreBundle\Form\Type\CurriculumInventorySequenceBlockType]
    ilioscore.curriculuminventorysequence.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.curriculuminventorysequence.manager", '@form.factory', Ilios\CoreBundle\Form\Type\CurriculumInventorySequenceType]
    ilioscore.department.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.department.manager", '@form.factory', Ilios\CoreBundle\Form\Type\DepartmentType]
    ilioscore.ilmsession.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.ilmsession.manager", '@form.factory', Ilios\CoreBundle\Form\Type\IlmSessionType]
    ilioscore.ingestionexception.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.ingestionexception.manager", '@form.factory', Ilios\CoreBundle\Form\Type\IngestionExeptionType]
    ilioscore.instructorgroup.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.instructorgroup.manager", '@form.factory', Ilios\CoreBundle\Form\Type\InstructorGroupType]
    ilioscore.learnergroup.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.learnergroup.manager", '@form.factory', Ilios\CoreBundle\Form\Type\LearnerGroupType]
    ilioscore.learningmaterial.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.learningmaterial.manager", '@form.factory', Ilios\CoreBundle\Form\Type\LearningMaterialType]
    ilioscore.learningmaterialstatus.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.learningmaterialstatus.manager", '@form.factory', Ilios\CoreBundle\Form\Type\LearningMaterialStatusType]
    ilioscore.learningmaterialuserrole.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.learningmaterialuserrole.manager", '@form.factory', Ilios\CoreBundle\Form\Type\LearningMaterialUserRoleType]
    ilioscore.meshconcept.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.meshconcept.manager", '@form.factory', Ilios\CoreBundle\Form\Type\MeshConceptType]
    ilioscore.meshdescriptor.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.meshdescriptor.manager", '@form.factory', Ilios\CoreBundle\Form\Type\MeshDescriptorType]
    ilioscore.meshpreviousindexing.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.meshpreviousindexing.manager", '@form.factory', Ilios\CoreBundle\Form\Type\MeshPreviousIndexingType]
    ilioscore.meshqualifier.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.meshqualifier.manager", '@form.factory', Ilios\CoreBundle\Form\Type\MeshQualifierType]
    ilioscore.meshsemantictype.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.meshsemantictype.manager", '@form.factory', Ilios\CoreBundle\Form\Type\MeshSemanticTypeType]
    ilioscore.meshterm.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.meshterm.manager", '@form.factory', Ilios\CoreBundle\Form\Type\MeshTermType]
    ilioscore.meshtree.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.meshtree.manager", '@form.factory', Ilios\CoreBundle\Form\Type\MeshTreeType]
    ilioscore.objective.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.objective.manager", '@form.factory', Ilios\CoreBundle\Form\Type\ObjectiveType]
    ilioscore.offering.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.offering.manager", '@form.factory', Ilios\CoreBundle\Form\Type\OfferingType]
    ilioscore.permission.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.permission.manager", '@form.factory', Ilios\CoreBundle\Form\Type\PermissionType]
    ilioscore.pendinguserupdate.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.pendinguserupdate.manager", '@form.factory', Ilios\CoreBundle\Form\Type\PendingUserUpdateType]
    ilioscore.program.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.program.manager", '@form.factory', Ilios\CoreBundle\Form\Type\ProgramType]
    ilioscore.programyear.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.programyear.manager", '@form.factory', Ilios\CoreBundle\Form\Type\ProgramYearType]
    ilioscore.programyearsteward.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.programyearsteward.manager", '@form.factory', Ilios\CoreBundle\Form\Type\ProgramYearStewardType]
    ilioscore.report.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.report.manager", '@form.factory', Ilios\CoreBundle\Form\Type\ReportType]
    ilioscore.school.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.school.manager", '@form.factory', Ilios\CoreBundle\Form\Type\SchoolType]
    ilioscore.sessiondescription.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.sessiondescription.manager", '@form.factory', Ilios\CoreBundle\Form\Type\SessionDescriptionType]
    ilioscore.sessionlearningmaterial.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.sessionlearningmaterial.manager", '@form.factory', Ilios\CoreBundle\Form\Type\SessionLearningMaterialType]
    ilioscore.session.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.session.manager", '@form.factory', Ilios\CoreBundle\Form\Type\SessionType]
    ilioscore.sessiontype.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.sessiontype.manager", '@form.factory', Ilios\CoreBundle\Form\Type\SessionTypeType]
    ilioscore.term.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.term.manager", '@form.factory', Ilios\CoreBundle\Form\Type\TermType]
    ilioscore.usermadereminder.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.usermadereminder.manager", '@form.factory', Ilios\CoreBundle\Form\Type\UserMadeReminderType]
    ilioscore.user.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.user.manager", '@form.factory', Ilios\CoreBundle\Form\Type\UserType]
    ilioscore.userrole.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.userrole.manager", '@form.factory', Ilios\CoreBundle\Form\Type\UserRoleType]
    ilioscore.vocabulary.handler:
        class: "%ilioscore.form.handler.class%"
        arguments: ["@ilioscore.vocabulary.manager", '@form.factory', Ilios\CoreBundle\Form\Type\VocabularyType]
