parameters:
    ilioscore.basemanager.class: Ilios\CoreBundle\Entity\Manager\BaseManager
    ilioscore.dtomanager.class: Ilios\CoreBundle\Entity\Manager\DTOManager
    ilioscore.auditlog.manager.class: Ilios\CoreBundle\Entity\Manager\AuditLogManager
    ilioscore.authentication.manager.class: Ilios\CoreBundle\Entity\Manager\AuthenticationManager
    ilioscore.courselearningmaterial.manager.class: Ilios\CoreBundle\Entity\Manager\CourseLearningMaterialManager
    ilioscore.course.manager.class: Ilios\CoreBundle\Entity\Manager\CourseManager
    ilioscore.curriculuminventoryreport.manager.class: Ilios\CoreBundle\Entity\Manager\CurriculumInventoryReportManager
    ilioscore.learningmaterial.manager.class: Ilios\CoreBundle\Entity\Manager\LearningMaterialManager
    ilioscore.meshdescriptor.manager.class: Ilios\CoreBundle\Entity\Manager\MeshDescriptorManager
    ilioscore.objective.manager.class: Ilios\CoreBundle\Entity\Manager\ObjectiveManager
    ilioscore.offering.manager.class: Ilios\CoreBundle\Entity\Manager\OfferingManager
    ilioscore.pendinguserupdate.manager.class: Ilios\CoreBundle\Entity\Manager\PendingUserUpdateManager
    ilioscore.programyearsteward.manager.class: Ilios\CoreBundle\Entity\Manager\ProgramYearStewardManager
    ilioscore.school.manager.class: Ilios\CoreBundle\Entity\Manager\SchoolManager
    ilioscore.sessiondescription.manager.class: Ilios\CoreBundle\Entity\Manager\SessionDescriptionManager
    ilioscore.sessionlearningmaterial.manager.class: Ilios\CoreBundle\Entity\Manager\SessionLearningMaterialManager
    ilioscore.user.manager.class: Ilios\CoreBundle\Entity\Manager\UserManager

services:
    ilioscore.aamcmethod.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\AamcMethod]
    ilioscore.aamcpcrs.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\AamcPcrs]
    ilioscore.aamcresourcetype.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\AamcResourceType]
    ilioscore.alertchangetype.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\AlertChangeType]
    ilioscore.alert.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\Alert]
    ilioscore.applicationconfig.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\ApplicationConfig]
    ilioscore.assessmentoption.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\AssessmentOption]
    ilioscore.auditlog.manager:
        class: "%ilioscore.auditlog.manager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\AuditLog]
    ilioscore.authentication.manager:
        class: "%ilioscore.authentication.manager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\Authentication]
    ilioscore.cohort.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\Cohort]
    ilioscore.competency.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\Competency]
    ilioscore.courseclerkshiptype.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\CourseClerkshipType]
    ilioscore.courselearningmaterial.manager:
        class: "%ilioscore.courselearningmaterial.manager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\CourseLearningMaterial]
    ilioscore.course.manager:
        class: "%ilioscore.course.manager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\Course]
    ilioscore.curriculuminventoryacademiclevel.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\CurriculumInventoryAcademicLevel]
    ilioscore.curriculuminventoryexport.manager:
        class: "%ilioscore.basemanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\CurriculumInventoryExport]
    ilioscore.curriculuminventoryinstitution.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\CurriculumInventoryInstitution]
    ilioscore.curriculuminventoryreport.manager:
        class: "%ilioscore.curriculuminventoryreport.manager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\CurriculumInventoryReport]
    ilioscore.curriculuminventorysequenceblock.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\CurriculumInventorySequenceBlock]
    ilioscore.curriculuminventorysequence.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\CurriculumInventorySequence]
    ilioscore.department.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\Department]
    ilioscore.ilmsession.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\IlmSession]
    ilioscore.ingestionexception.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\IngestionException]
    ilioscore.instructorgroup.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\InstructorGroup]
    ilioscore.learnergroup.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\LearnerGroup]
    ilioscore.learningmaterial.manager:
        class: "%ilioscore.learningmaterial.manager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\LearningMaterial]
    ilioscore.learningmaterialstatus.manager:
        class: "%ilioscore.basemanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\LearningMaterialStatus]
    ilioscore.learningmaterialuserrole.manager:
        class: "%ilioscore.basemanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\LearningMaterialUserRole]
    ilioscore.meshconcept.manager:
        class: "%ilioscore.basemanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\MeshConcept]
    ilioscore.meshdescriptor.manager:
        class: "%ilioscore.meshdescriptor.manager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\MeshDescriptor]
    ilioscore.meshpreviousindexing.manager:
        class: "%ilioscore.basemanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\MeshPreviousIndexing]
    ilioscore.meshqualifier.manager:
        class: "%ilioscore.basemanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\MeshQualifier]
    ilioscore.meshsemantictype.manager:
        class: "%ilioscore.basemanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\MeshSemanticType]
    ilioscore.meshterm.manager:
        class: "%ilioscore.basemanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\MeshTerm]
    ilioscore.meshtree.manager:
        class: "%ilioscore.basemanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\MeshTree]
    ilioscore.objective.manager:
        class: "%ilioscore.objective.manager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\Objective]
    ilioscore.offering.manager:
        class: "%ilioscore.offering.manager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\Offering]
    ilioscore.permission.manager:
        class: "%ilioscore.basemanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\Permission]
    ilioscore.pendinguserupdate.manager:
        class: "%ilioscore.pendinguserupdate.manager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\PendingUserUpdate]
    ilioscore.program.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\Program]
    ilioscore.programyear.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\ProgramYear]
    ilioscore.programyearsteward.manager:
        class: "%ilioscore.programyearsteward.manager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\ProgramYearSteward]
    ilioscore.report.manager:
        class: "%ilioscore.basemanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\Report]
    ilioscore.school.manager:
        class: "%ilioscore.school.manager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\School]
    ilioscore.schoolconfig.manager:
        class: "%ilioscore.basemanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\SchoolConfig]
    ilioscore.sessiondescription.manager:
        class: "%ilioscore.sessiondescription.manager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\SessionDescription]
    ilioscore.sessionlearningmaterial.manager:
        class: "%ilioscore.sessionlearningmaterial.manager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\SessionLearningMaterial]
    ilioscore.session.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\Session]
    ilioscore.sessiontype.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\SessionType]
    ilioscore.term.manager:
        class: "%ilioscore.dtomanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\Term]
    ilioscore.usermadereminder.manager:
        class: "%ilioscore.basemanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\UserMadeReminder]
    ilioscore.user.manager:
        class: "%ilioscore.user.manager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\User, '@ilioscore.usermaterial.factory']
    ilioscore.userrole.manager:
        class: "%ilioscore.basemanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\UserRole]
    ilioscore.vocabulary.manager:
        class: "%ilioscore.basemanager.class%"
        arguments: ['@doctrine', Ilios\CoreBundle\Entity\Vocabulary]
