services:
    filesystem:
        class: Symfony\Component\Filesystem\Filesystem
    ilioscore.listener.logentitychanges:
        class: Ilios\CoreBundle\EventListener\LogEntityChanges
        tags:
            - { name: doctrine.event_listener, event: onFlush }
        calls:
            - [ setContainer, ['@service_container'] ]
    ilioscore.listener.trackapiusage:
        class: Ilios\CoreBundle\EventListener\TrackApiUsageListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        arguments: ['%ilios_core.enable_tracking%', '@happyr.google_analytics.tracker', '@logger']
    ilioscore.listener.timestampentity:
        class: Ilios\CoreBundle\EventListener\TimestampEntityChanges
        arguments: ['@ilioscore.timestamper']
        tags:
            - { name: doctrine.event_listener, event: onFlush }
    ilioscore.dataimport_filelocator:
        class: Ilios\CoreBundle\Classes\DataimportFileLocator
        arguments: [ '@file_locator' ]
    ilioscore.temporary_filesystem:
        class: Ilios\CoreBundle\Classes\TemporaryFileSystem
        arguments: ['@filesystem', "%kernel.root_dir%"]
    ilioscore.filesystem:
        class: Ilios\CoreBundle\Classes\IliosFileSystem
        arguments: ['@filesystem', "%ilios_core.file_store_path%"]
    ilioscore.symfonyfilesystem:
        class: Ilios\CoreBundle\Classes\Filesystem
    ilioscore.logger:
        class: Ilios\CoreBundle\Service\Logger
        arguments: ['@security.token_storage', '@ilioscore.auditlog.manager']
    ilioscore.logger.queue:
        class: Ilios\CoreBundle\Service\LoggerQueue
        arguments: ['@ilioscore.logger']
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: flush }
            - { name: kernel.event_listener, event: console.terminate, method: flush }
    ilioscore.ldapmanager:
        class: Ilios\CoreBundle\Service\LdapManager
        arguments: ['%ilios_core.ldap.url%', '%ilios_core.ldap.user%', '%ilios_core.ldap.password%', '%ilios_core.ldap.search_base%', '%ilios_core.ldap.campus_id_property%', '%ilios_core.ldap.username_property%']
    ilioscore.directory:
        class: Ilios\CoreBundle\Service\Directory
        arguments: ['@ilioscore.ldapmanager', '%ilios_core.ldap.campus_id_property%']
    ilioscore.curriculum_inventory.exporter:
        class: Ilios\CoreBundle\Service\CurriculumInventory\Exporter
        arguments: [ "@ilioscore.curriculuminventoryreport.manager", "@ilioscore.curriculuminventoryinstitution.manager", "%ilios_core.institution_domain%", "%ilios_core.supporting_link%" ]
    ilioscore.curriculum_inventory.rollover:
        class: Ilios\CoreBundle\Service\CurriculumInventory\ReportRollover
        arguments: [ "@ilioscore.curriculuminventoryreport.manager", "@ilioscore.curriculuminventoryacademiclevel.manager", "@ilioscore.curriculuminventorysequence.manager", "@ilioscore.curriculuminventorysequenceblock.manager"]
    ilioscore.learningmaterial_decorator.factory:
        class: Ilios\CoreBundle\Service\LearningMaterialDecoratorFactory
        arguments: [ "@router", Ilios\CoreBundle\Classes\LearningMaterialDecorator ]
    ilioscore.curriculum_inventory_report_decorator.factory:
            class: Ilios\CoreBundle\Service\CurriculumInventoryReportDecoratorFactory
            arguments: [ "@router", Ilios\CoreBundle\Classes\CurriculumInventoryReportDecorator ]
    ilioscore.form.transformer.html_purifier:
        class: Exercise\HTMLPurifierBundle\Form\HTMLPurifierTransformer
        arguments: ["@exercise_html_purifier.default"]
    ilioscore.courserollover:
        class: Ilios\CoreBundle\Classes\CourseRollover
        arguments: ["@ilioscore.course.manager","@ilioscore.learningmaterial.manager","@ilioscore.courselearningmaterial.manager","@ilioscore.session.manager","@ilioscore.sessiondescription.manager","@ilioscore.sessionlearningmaterial.manager","@ilioscore.offering.manager", "@ilioscore.objective.manager", "@ilioscore.ilmsession.manager"]
    ilioscore.usermaterial.factory:
        class: Ilios\CoreBundle\Service\UserMaterialFactory
        arguments: [ "@router", Ilios\CoreBundle\Classes\UserMaterial ]
    ilioscore.timestamper:
        class: Ilios\CoreBundle\Service\Timestamper
        arguments: [ "@doctrine" ]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: flush }
            - { name: kernel.event_listener, event: console.terminate, method: flush }
