imports:
    - { resource: virtual-managers.yml }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ilios\CoreBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Exception,Controller}'

    Ilios\CoreBundle\Entity\Manager\:
        resource: '../../Entity/Manager'

    Ilios\CoreBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Ilios\CoreBundle\Service\EntityMetadata:
        arguments:
          $cache: '@ilios.cache'

    Ilios\CoreBundle\EventListener\LogEntityChanges:
        tags:
            - { name: doctrine.event_listener, event: onFlush }
        calls:
            - [ setContainer, ['@service_container'] ]

    Ilios\CoreBundle\EventListener\TrackApiUsageListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    Ilios\CoreBundle\EventListener\TimestampEntityChanges:
        tags:
          - { name: doctrine.event_listener, event: onFlush }

    Ilios\CoreBundle\Service\Config:
        public: true

    Ilios\CoreBundle\Service\DataimportFileLocator:
        public: true

    Ilios\CoreBundle\Service\Filesystem:
        public: true

    Ilios\CoreBundle\Service\Directory:
      public: true

    Ilios\CoreBundle\Service\TemporaryFileSystem:
        arguments:
          $kernelRootDirectory: '%kernel.root_dir%'

    Ilios\CoreBundle\Service\LoggerQueue:
        public: true
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: flush }
            - { name: kernel.event_listener, event: console.terminate, method: flush }

    Ilios\CoreBundle\Service\CurriculumInventoryReportDecoratorFactory:
        arguments:
            $decoratorClassName: '\Ilios\CoreBundle\Classes\CurriculumInventoryReportDecorator'

    Ilios\CoreBundle\Service\Timestamper:
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: flush }
            - { name: kernel.event_listener, event: console.terminate, method: flush }

    Ilios\CoreBundle\Service\UserMaterialFactory:
        arguments:
            $decoratorClassName: '\Ilios\CoreBundle\Classes\UserMaterial'

    ilios.cache:
        class: 'Doctrine\Common\Cache\Cache'
        factory: ['Ilios\CoreBundle\Service\CacheFactory', 'createCache']
        arguments:
            $environment: '%kernel.environment%'

    Ilios\CoreBundle\Controller\ExceptionController:
        public: true
        arguments:
            $environment: '%kernel.environment%'

    Ilios\CoreBundle\Service\CrossingGuard:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 256 }

    Alchemy\Zippy\Zippy:
        factory: ['Alchemy\Zippy\Zippy', 'load']

    Ilios\CoreBundle\Entity\Manager\AlertManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\Alert'
    Ilios\CoreBundle\Entity\Manager\AlertChangeTypeManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\AlertChangeType'
    Ilios\CoreBundle\Entity\Manager\ApplicationConfigManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\ApplicationConfig'
    Ilios\CoreBundle\Entity\Manager\AuditLogManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\AuditLog'
    Ilios\CoreBundle\Entity\Manager\AuthenticationManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\Authentication'
    Ilios\CoreBundle\Entity\Manager\CourseManager:
        public: true
        class: Ilios\CoreBundle\Entity\Manager\CourseManager
        arguments:
            $class: 'Ilios\CoreBundle\Entity\Course'
    Ilios\CoreBundle\Entity\Manager\CourseLearningMaterialManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\CourseLearningMaterial'
    Ilios\CoreBundle\Entity\Manager\CurriculumInventoryAcademicLevelManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\CurriculumInventoryAcademicLevel'
    Ilios\CoreBundle\Entity\Manager\CurriculumInventoryExportManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\CurriculumInventoryExport'
    Ilios\CoreBundle\Entity\Manager\CurriculumInventoryInstitutionManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\CurriculumInventoryInstitution'
    Ilios\CoreBundle\Entity\Manager\CurriculumInventoryReportManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\CurriculumInventoryReport'
    Ilios\CoreBundle\Entity\Manager\CurriculumInventorySequenceBlockManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\CurriculumInventorySequenceBlock'
    Ilios\CoreBundle\Entity\Manager\CurriculumInventorySequenceManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\CurriculumInventorySequence'
    Ilios\CoreBundle\Entity\Manager\IlmSessionManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\IlmSession'
    Ilios\CoreBundle\Entity\Manager\LearningMaterialManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\LearningMaterial'
    Ilios\CoreBundle\Entity\Manager\MeshDescriptorManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\MeshDescriptor'
    Ilios\CoreBundle\Entity\Manager\ObjectiveManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\Objective'
    Ilios\CoreBundle\Entity\Manager\OfferingManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\Offering'
    Ilios\CoreBundle\Entity\Manager\PendingUserUpdateManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\PendingUserUpdate'
    Ilios\CoreBundle\Entity\Manager\ProgramYearStewardManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\ProgramYearSteward'
    Ilios\CoreBundle\Entity\Manager\SchoolManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\School'
    Ilios\CoreBundle\Entity\Manager\SessionManager:
        public: true
        class: Ilios\CoreBundle\Entity\Manager\SessionManager
        arguments:
            $class: 'Ilios\CoreBundle\Entity\Session'
    Ilios\CoreBundle\Entity\Manager\SessionDescriptionManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\SessionDescription'
    Ilios\CoreBundle\Entity\Manager\SessionLearningMaterialManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\SessionLearningMaterial'
    Ilios\CoreBundle\Entity\Manager\UserManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\User'
    Ilios\CoreBundle\Entity\Manager\UserRoleManager:
        public: true
        arguments:
            $class: 'Ilios\CoreBundle\Entity\UserRole'
